source "https://rubygems.org"

gem "rspec-celluloid", :path => "../.."
platforms :jruby do
  gem 'activerecord-jdbc-adapter', :require => false
end
platforms :jruby do
  gem 'jdbc-sqlite3', :require => false
end
platforms :ruby do
  gem "sqlite3"
end
gem "activerecord"
gem "rspec"
